### ISSUE TITLE
Is it possible to authenticate in Harvest using LDAP or Azure SSO?

### ISSUE THREAD

**Issue by rkale88** [Strategery-Inc/jira-harvest-time-tracker#104]
All current users are just given their set of username and password. We currently have Harvest integrated with our Jira instance. 
Is it possible to authenticate in Harvest using LDAP or Azure SSO?

**Comment by gsomoza** [comment]
This plugin uses OAuth in order to request access to a user's Harvest account via the Harvest API. This means the JIRA user is sent to a Harvest authentication screen where they can "allow" the plugin to access their account's API. That screen belongs to the Harvest platform, so the user would have to log into Harvest using whatever authentication mechanism is configured for their Harvest account. In theory that would include SSO.

The step of allowing access to the Harvest account is not something we can avoid at the moment because we don't have a backend server for this plugin: all the code runs in the user's browser and all data is stored there as well.

FYI I'll close this ticket just because, at least for now, it doesn't represent pending work to be done in the plugin. But we can keep the conversation going if you have any questions even while the ticket is closed.
