### ISSUE TITLE
Stopping time directly from Harvest doesn't log work into JIRA

### ISSUE THREAD

**Issue by sdishman** [Strategery-Inc/jira-harvest-time-tracker#12]
Steps to reproduce:
1. Using the Harvest plugin for JIRA, click "Track Time".
2. Start a running timer.
3. Using the Harvest website (or app, etc.) stop the running timer created by the plugin.

The plugin will correctly reflect the fact that the timer isn't running anymore (button says "Track Time" now instead of "Start Timer", but nothing ever gets added to the JIRA work history.

We are currently evaluating the plugin on a free trial and, so far, this is the primary deal-breaker.  I cannot have time getting lost if my engineers choose to stop their tracking one way versus another.

**Comment by RCheesley** [comment]
@sdishman just responding to your situation above. We have an internal project in Jira in which we have issues for things like meetings, communication, support etc.  That way everything can be logged in Jira although it's a faff to have to log time against them because you have to find and open them if we were going to use the harvest/jira integration.

We tend to use Tempo's worklog calendar in Jira however that has the downside of time not being logged in Harvest if it is entered on the worklog, as that uses Jira's in-built time logging and not the 'press this button to log time in harvest'.

So my dilemma at the moment is whether Harvest is a suitable replacement for tempo worklog, but I can see coming up against similar problems as you have mentioned, people starting in Jira and stopping somewhere else!

It's a shame that there isn't the ability to suck the time logs from Jira directly and dump them into Harvest :(

**Comment by gsomoza** [comment]
@RCheesley we currently don't push JIRA worklogs to Harvest, because that may work for one team it could break another team's workflow. It seems that for you, rather than using JIRA in the middle, a direct integration between Tempo and Harvest might be a better solution. But I'm not aware of any solutions for that ATM..
