### ISSUE TITLE
Admin: Mapping of Harvest Projects to JIRA Projects

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/jira-harvest-time-tracker#46]
Add a tool in the admin configuration section to allow Admins to map Harvest projects to JIRA projects. I will refer to this configuration as the "Admin Mapping" throughout this ticket. 

When a user opens a JIRA ticket the following use-cases should be considered:

A. If its a user with no mappings (e.g. a new user).
1. If an "Admin Mapping" exists for the current JIRA project then use that value as the default for the "Project" field in the time-tracking form.
2. Once a user tracked time on a certain project, save a setting _at the user's level_ (I'll refer to this as "User Mapping") that will map whichever Harvest project the user selected to the JIRA project that the current ticket belongs to. This will transition the user to use-case B the next time that he tries to track time on this particular JIRA project.

B. User with an existing "User Mapping" for the current JIRA project.
1. If a "User Mapping" exists for the JIRA project then this should take precedence over all other rules. This will allow specific users to track time on specific projects if they choose to. The "User Mapping" for the current JIRA project should be overwritten as soon as the user tracks a time-entry using a different Harvest project than the one saved in the mapping.
2. If no "User Mapping" exists for the current JIRA project then the "Admin Mapping" should be used. And if that "Admin Mapping" doesn't have any mappings for the current project then default to blank (no default project selected).

**Comment by danielfaulknor** [comment]
Any progress on this? It's the only blocker to us purchasing the add-on

**Comment by gsomoza** [comment]
It's still far down in our backlog, because we just released a new version of the plugin with a complete rewrite.

However, we're still considering whether this feature is worth it's complexity, for the following reasons:
1. Project visibility on a per-user level can already be configured in both Harvest and JIRA. Our plugin honors that configuration: a user will only see the projects they were assigned to.
2. This plugin already tries to pre-select the correct project by default: if the project code in Harvest matches (at least partly) the project code in JIRA, then the "Project" drop-down will already be per-populated so that the user can track time without having to manually select the project each time. 

With those two existing features in mind it's hard for us to justify adding so much complexity to our plugin, and the investment that would require. 

Having said that, if enough users want this feature (i.e. there are good indications it would increase sales or customer satisfaction by a considerable factor) then we will probably implement it. How many users would be using this plugin in your company if you decided to purchase a license? Feel free to email that information to contact (at) strategery (dot) io

**Comment by danielfaulknor** [comment]
Probably not enough users for you to consider it worthwhile!

The official Harvest plugin for JIRA remembers per project, so I've migrated to JIRA Cloud and will use that instead. I really appreciate you taking the time to respond

**Comment by gsomoza** [comment]
We also have a JIRA Cloud version of this same plugin by the way. But it will also try to match the projects by key: it won't really "remember" it if the keys don't match.

I'll keep this ticket open in case other people want to upvote it.

**Comment by b2brpm** [comment]
Our use case for this is as follows:
We launch projects with our clients across different countries and they would like us to separate out the hours by country. 
The idea is that a project manager should specify the Harvest project / task at the time the issue is created so that the developer books his time accordingly.
I think we're going to simply do this as a text field for now, but thought I would dispute the comment by Daniel above!
Thanks so much for this product!

**Comment by gsomoza** [comment]
Thanks for sharing your use-case, we'll keep it into consideration as well, and I'm glad you're finding the plugin useful!

**Comment by markadrake** [comment]
This really isn't about giving the resource options to bill to, this is about controlling where your resources put their time to so that time reporting is consistent across the team and accurate per the expectations of the PM/PO. I think this provides a very useful feature set. To apply a default Project and Task at the **project level**, and to further modify that on the **epic level** - PM's can ensure that the team is consistent with where their hours are placed. I'd suggest that in this instance (a project/task has been identified) that you don't even show these 2 fields when reporting time.

**Comment by gsomoza** [comment]
Closing this ticket for now, because implementing this feature would involve adding a lot of complexity to the stack and would make the plugin much harder to maintain (= more expensive). Will re-open if this becomes feasible in the future...
