### ISSUE TITLE
Jira Cloud. Harvest Plugin is not responding. Please help

### ISSUE THREAD

**Issue by estan1** [Strategery-Inc/jira-harvest-time-tracker#56]
Hey,

We are at Jira Cloud and use the Harvest plugin extensively.
It stopped working in the last hours though. It says that it does not respond. See the image attached below:
![harvest](https://cloud.githubusercontent.com/assets/1336015/10228011/5d0175a4-6879-11e5-9639-0ac03dcc8345.png)

I tried disable and re-enable it but it did not help. 

Can you help please? Is this something with your servers being down? Or is the issue about something else?

**Comment by estan1** [comment]
Some hours later seems to be ok. Very odd. Is this a server issue?

Please check anyway.

**Comment by estan1** [comment]
Hmmm, it does not work again. Still server issues or something else?

**Comment by gabrielsomoza** [comment]
Hi @estan1 - yes, we're having server issues. Looks related to SSL but we're trying to narrow it down.

**Comment by longwave** [comment]
Also seeing this, there is an SSL internal error:

```
$ openssl s_client -connect harvest-jira.usestrategery.com:443
CONNECTED(00000003)
140246521841312:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

**Comment by gabrielsomoza** [comment]
We put the server that's failing offline and are debugging it to see what happened. Meanwhile a new one is replacing it temporarily. We'll keep you updated if we find the issue.

**Comment by gabrielsomoza** [comment]
The issue was a DNS replication problem when we moved our domain to the CloudFlare nameservers. The process should have been completely transparent because DNS records were configured properly in both the old and new nameservers, but for some reason during the propagation period the MediaTemple nameservers started to resolve "usestrategery.com" and a few of its sub-domains to the wrong IP address.

We contacted them to inquire about what could have caused the issue, especially since the settings were correct in our end.

Whatever the issue was: propagation is now finished and the domain will be resolved with CloudFlare from now on. This is good news, we can finally enjoy several long-term benefits like: better security against certain types of attacks (e.g. DoS), better DNS tools, monitoring, etc. This should in turn result in less issues like this in the future.

Apologies for the bumpy ride, and thanks for your patience!
