### ISSUE TITLE
plugin fails to connect to Harvest

### ISSUE THREAD

**Issue by andrewmallis** [Strategery-Inc/jira-harvest-time-tracker#60]
This is sudden.
![_eecs-6__set_up_pantheon_environment_-_jira](https://cloud.githubusercontent.com/assets/249362/11104140/b643cfd2-887b-11e5-8931-7ba02a360644.png)

Tried disabling/re-enabling and unsubscribing+uninstalling+resubscribing but no luck

**Comment by gabrielsomoza** [comment]
For the "host" part try entering only the first part (the one that's blurred out). Let me know if that helps. We're going to make that easier in upcoming versions.

**Comment by andrewmallis** [comment]
Did not work. Things worked previously with that host pattern.

Harvest has a new single sign on service, Harvest ID, to facilitate access across both Harvest and Forecast.

It is not super obvious that you need to convert and sign up for this service or everything breaks.

Harvest sent out an email with the subject line
*Harvest ID is here! New Password Required*


the login link for Harvest now goes to https://id.getharvest.com/sessions/new
but you can auth with Google and get in just fine.
That's what I did and have been doing.
It does not suffice. I _think_ you actually need to click through the email to get things converted properly. A new email is triggered by submitting the password reset form at https://id.getharvest.com/password_reset/new

**Comment by andrewmallis** [comment]
so, creating a new SSO ID with Harvest does let Jira log in again.

**Comment by gabrielsomoza** [comment]
Thanks for the information Andrew! 

The Harvest's API that we consume didn't change - including the authentication mechanism that we use - so as long as we can continue to send authentication information through that API our plugin should keep on working. 

With that in mind, this looks like an account issue on Harvest's side - rather than on our extension. And it sounds like their migration to a centralised SSO system could have been smoother.. If you have any further issues with that then I recommend you get in touch with their support team.

Thanks again for reporting this! I'm sure it will help other people going through similar problems. I'll close the ticket for now - but we can re-open if we find anything that we can do to help on our end.
