### ISSUE TITLE
Plug in fails when your website goes down

### ISSUE THREAD

**Issue by andrewmallis** [Strategery-Inc/jira-harvest-time-tracker#62]
Your websites are down: https://harvest-jira.usestrategery.com &  https://harvest-jira.usestrategery.com which causes the plug in to fail.

Is there any way to handle this error more gracefully?

**Comment by centerlinescores** [comment]
Also, any idea when the site will actually be up?

**Comment by gabrielsomoza** [comment]
Its up now, and we'll restart the web-server every hour until we find why its randomly freezing up, because its obviously a recurring problem.

We're also considering moving the plugin to a separate server, but this isn't a straightforward decision because we're not making enough money with it to justify a dedicated server (at least not at the same pricing tier as the current one) or a more robust setup...

We'll keep this open for future updates.

**Comment by gabrielsomoza** [comment]
We moved to new servers that have auto-scaling capabilities. We'll monitor them for a few weeks to make sure what we have can cover the average demand. If you have any issues please let us know through this ticket and we'll re-open it if necessary.
