### ISSUE TITLE
Start time tracking from Scrum / Kanban boards in Download version

### ISSUE THREAD

**Issue by hankthetank** [Strategery-Inc/jira-harvest-time-tracker#74]
We are using the download version of the plugin and have also switched to using the boards feature in latest JIRA. The problem now is that when I want to track time on an issue that I move to the "In progress" silo, I can not start time directly in the boards view. I need to go to the normal issue view first. Also it would be extra cool if you could add a setting that time tracking dialog showed up when moved to "In progress".

**Comment by gsomoza** [comment]
Unfortunately this isn't currently possible because the API for the Scrum / Kanban boards plugin isn't properly documented and there aren't enough "hooks" we could use to make this easily. It would take A LOT of work, reverse engineering and testing it.

We really want this feature too, so we will re-open this ticket (or a new one) and introduce it once we find a viable way of implementing it. If you're already using a plugin you'll receive an email with the update!
