### ISSUE TITLE
New Plugin Version – Upgrade Plan for Existing Customers

### ISSUE THREAD

**Issue by wbrands2** [Strategery-Inc/jira-harvest-time-tracker#90]
Do I need to repurchase this in order to get new features?!

https://marketplace.atlassian.com/apps/1219223/harvester-real-time-tracking?hosting=server&tab=overview

**Comment by gsomoza** [comment]
Cloud users (who are paying a recurring subscription) won't have to re-purchase because we're planning to back-port any new features and bug fixes. We'll send out an email with more details and a roadmap before the end of the year.

On-Premise users should be able to continue using the version they paid for until their license expires. At that point we would recommend them to consider switching to this new plugin. For users who want to switch earlier we'll send an adjusted (pro-rated) discount code. 

You can expect an email about this soon too, but if you want to make the switch right now please email us at contact (at) strategery (dot) io with your current license information and I'll send you the discount code so you can make the switch. Keep in mind you can also start a trial version of the new plugin before deciding whether you want to purchase the new license.

**Comment by gsomoza** [comment]
Closing: an email was sent to all customers with new instructions
